spring.application.name=notifyhub

spring.datasource.url = ${DATABASE_URL}

spring.datasource.username = ${DATABASE_USERNAME}
spring.datasource.password = ${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update


jwt.secret = ${JWT_SECRET}



spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


resend.api.key = ${RESEND_API_KEY}


spring.data.redis.host = ${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}


# Reduce connection pool size
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=300000

# Reduce Tomcat threads
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=5